[package]
name = "adit-sync"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
adit-domain.workspace = true
adit-storage.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
ureq.workspace = true
sha2.workspace = true
hmac.workspace = true
hex.workspace = true
